### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by nixmeer** [Skinner927/alexa-findmyiphone#2]
Hello,

is there instructions on how to set this up? I have no experience with coding for Alexa.

Is the Amazon AWS for this free? Otherwise I got a server running my webpage.

Best
Jan

**Comment by Skinner927** [comment]
Did you bother to read the readme? There are instructions there.

Running lambda is not free (AFAIK). You'll need to self-host on a server that support python wsgi (uwsgi, gunicorn, etc.)

After you've read the readme, if you are still confused or need clarification please let me know.
