### ISSUE TITLE
Invalid icloud email or password for ...

### ISSUE THREAD

**Issue by davidohne** [Skinner927/alexa-findmyiphone#3]
There seems to be a problem with the login through pyicloud. I reeeeeealy checked everything and also installed pyicloud itself to recognize that it's not possible to log into the icloud services through pyicloud at the moment. So if anyone tries to install now: I think it can't work at the moment. Or does anyone know how to make the login work again?

Here is the issue report in pyicloud: https://github.com/picklepete/pyicloud/issues/206

**Comment by Skinner927** [comment]
I'm aware of the login issue and you are correct that it's because of `pyicloud`. I've been subscribed to the issue and will bump my dependency if/when they release an update. I haven't had a chance to look into it myself to see if I can help.

**Comment by Skinner927** [comment]
I'm closing this issue because pyicloud is working again
