### ISSUE TITLE
Instruction libapache2-mod-wsgi to libapache2-mod-wsgi-py3

### ISSUE THREAD

**Issue by davidohne** [Skinner927/alexa-findmyiphone#4]
Hey!
Don't we need the libapache2-mod-wsgi-py3 package for python3 environment? The instruction wants the libapache2-mod-wsgi version.

**Comment by Skinner927** [comment]
You are correct. I guess I didn't bump the readme when I swapped over to Python3. If you wanna do a PR with any tweaks you may have found during the install please feel free.
